    Data creation - numpy

    Data cleansing, wrangling, maniulation - pandas

    data visualisation( matploit, bokeh, seaborn, plotly)

In [1]:
import numpy as np
import pandas as pd

In [2]:
z = np.random.randn(5,5)
z

array([[-1.8571067 , -0.46621436,  1.11048256,  1.01845276,  0.40251916],
       [ 0.48176011, -0.54259946,  0.15683946,  0.95202954,  0.25253862],
       [-1.12032341,  0.16707988, -0.52713565,  1.92084254,  0.01875882],
       [-0.06281492,  0.40553845, -1.93092373, -1.22382939,  1.71738399],
       [ 0.3267103 ,  1.13622739, -0.97566647,  1.41200662, -0.52958904]])

In [3]:
l=[1,2,3,4,5]
m={1,2,3,4,5}


In [4]:
s=np.array(l)
t=np.array(m)
print(s)
print(t)

[1 2 3 4 5]
set([1, 2, 3, 4, 5])


In [5]:
print (np.arange(4,100,5))

[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99]


In [6]:
%time
l=[1,2,3,4,5]
s=np.array(l)
print(s+3)
s+=2
print(s)
s+=1
print(s)

Wall time: 0 ns
[4 5 6 7 8]
[3 4 5 6 7]
[4 5 6 7 8]


In [7]:
print (np.zeros((5,5)),)
print (np.zeros(5))


(array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]]),)
[0. 0. 0. 0. 0.]


In [8]:
np.linspace(5,30,5)

array([ 5.  , 11.25, 17.5 , 23.75, 30.  ])

In [9]:
np.random.randint(100)

93

In [10]:
k=np.zeros(16)
print(k)
print(k.reshape(2,4,2))
print(k.ravel())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
print(k.reshape(2,2,4)) 

print(k.reshape(2,2,2,2))

print(k.reshape(4,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
o = np.arange(50,100,5)
o

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [13]:
np.savetxt("first file.csv",X=o)
np.savetxt("first file.pdf",X=o)

np.savetxt("first file",X=o)



In [14]:
import os


In [15]:
os.getcwd()

'C:\\Users\\umama'

In [22]:

np.loadtxt("first file")

array([50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62.,
       63., 64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75.,
       76., 77., 78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88.,
       89., 90., 91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [17]:
np.loadtxt('first file')

array([50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62.,
       63., 64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75.,
       76., 77., 78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88.,
       89., 90., 91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [18]:
np.loadtxt("first file.pdf")

array([50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62.,
       63., 64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75.,
       76., 77., 78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88.,
       89., 90., 91., 92., 93., 94., 95., 96., 97., 98., 99.])