In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv('Social_Network_Ads.csv')
df


User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
x=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values
x


array([['Male', 19L, 19000L],
       ['Male', 35L, 20000L],
       ['Female', 26L, 43000L],
       ...,
       ['Female', 50L, 20000L],
       ['Male', 36L, 33000L],
       ['Female', 49L, 36000L]], dtype=object)

from sklearn.preprocessing import Imputer


i=Imputer(missing_values='NaN',strategy='mean')
x[:,1:3]=i.fit_transform(x[:,1:3])
i=i.fit(x[:,1:3])
x[:,1:3]=i.transform(x[:,1:3])
print(x)


x[:,1:3]=i.fit_transform(x[:,1:3])
x

In [4]:
from sklearn.preprocessing import LabelEncoder as le
l=le()
x[:,0]=l.fit_transform(x[:,0])
x

array([[1, 19L, 19000L],
       [1, 35L, 20000L],
       [0, 26L, 43000L],
       ...,
       [0, 50L, 20000L],
       [1, 36L, 33000L],
       [0, 49L, 36000L]], dtype=object)

from sklearn.preprocessing import OneHotEncoder as oc
o=oc(categorical_features=[0])
x=o.fit_transform(x).toarray()
x

In [5]:
from sklearn.model_selection import train_test_split as tt
xtrain, xtest,ytrain,ytest=tt(x,y,test_size=0.3)
xtest


array([[0, 23L, 48000L],
       [0, 23L, 66000L],
       [0, 36L, 63000L],
       [0, 47L, 107000L],
       [0, 27L, 58000L],
       [0, 34L, 43000L],
       [0, 40L, 75000L],
       [1, 49L, 86000L],
       [0, 53L, 82000L],
       [1, 38L, 61000L],
       [1, 35L, 88000L],
       [0, 33L, 41000L],
       [1, 46L, 79000L],
       [0, 35L, 77000L],
       [0, 46L, 82000L],
       [1, 35L, 73000L],
       [0, 37L, 80000L],
       [0, 48L, 134000L],
       [0, 27L, 31000L],
       [1, 36L, 33000L],
       [0, 29L, 83000L],
       [0, 52L, 114000L],
       [1, 31L, 66000L],
       [0, 38L, 55000L],
       [1, 47L, 105000L],
       [0, 24L, 89000L],
       [1, 35L, 72000L],
       [0, 26L, 52000L],
       [1, 36L, 144000L],
       [1, 45L, 22000L],
       [0, 35L, 23000L],
       [1, 40L, 57000L],
       [0, 48L, 30000L],
       [1, 40L, 57000L],
       [1, 49L, 65000L],
       [1, 20L, 49000L],
       [1, 35L, 20000L],
       [0, 33L, 28000L],
       [0, 27L, 84000L],
       [0, 32L, 1170

In [6]:
from sklearn.preprocessing import StandardScaler as sc
s=sc()
xtrain=s.fit_transform(xtrain)
xtest=s.fit_transform(xtest)

print xtrain



[[ 1.02166316 -0.70988132 -0.57446814]
 [ 1.02166316 -0.51792886 -1.50580609]
 [-0.97879618  0.44183342  0.65730142]
 [-0.97879618 -1.09378623 -1.53584925]
 [-0.97879618  0.15390474  0.32682666]
 [ 1.02166316 -1.76561983 -1.47576293]
 [ 1.02166316  0.82573834  0.5972151 ]
 [-0.97879618 -0.42195263 -0.51438182]
 [ 1.02166316 -0.61390509 -0.3040797 ]
 [ 1.02166316 -0.61390509  0.17661086]
 [-0.97879618 -0.23000018 -0.33412286]
 [ 1.02166316 -1.18976246  0.56717194]
 [ 1.02166316 -0.70988132 -1.53584925]
 [ 1.02166316  0.15390474  1.61868254]
 [-0.97879618 -1.09378623  1.4985099 ]
 [-0.97879618  1.20964325  0.5972151 ]
 [ 1.02166316 -1.28573869  0.47704246]
 [ 1.02166316 -0.90183377  0.62725826]
 [-0.97879618  0.82573834  0.17661086]
 [-0.97879618 -0.90183377  0.50708562]
 [ 1.02166316  2.16940553 -0.78477025]
 [ 1.02166316 -0.23000018 -0.4542955 ]
 [-0.97879618 -0.90183377  0.47704246]
 [-0.97879618  0.63378588 -0.87489973]
 [ 1.02166316  0.15390474 -0.78477025]
 [ 1.02166316 -0.3259764 

C:\Users\umama\Anaconda2\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


from sklearn.preprocessing import StandardScaler as sc
s=sc()

xtrain=s.fit_transform(xtrain)
xtest=s.fit_transform(xtest)
xtrain


In [7]:
xtest.shape

(120L, 3L)

In [8]:
ytest.shape

(120L,)

In [16]:
from sklearn.naive_bayes import GaussianNB as gnb
nb = gnb()
nb.fit(xtrain,ytrain)
ypred = nb.predict(xtest).reshape(-1,1)
ypred

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
    

In [14]:
from sklearn.metrics import accuracy_score as ac
ac = nb.score(xtest,ytest)
ac*100

92.5

In [12]:
from sklearn.metrics import confusion_matrix as cm
cm=nb.score(xtest,ytest)
cm*100

92.5

In [ ]:
from sklearn.svm import SVR
svr=SVR()


In [ ]:
svr.fit(xtrain,ytrain)
ypred = svr.predict(xtest).reshape(-1,1)
ypred


In [ ]:
ac = svr.score(xtrain,ytrain)
ac*100

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()


In [ ]:
dtc.fit(xtrain,ytrain)
ypred = dtc.predict(xtest).reshape(-1,1)
ypred


In [ ]:
ac = dtc.score(xtrain,ytrain)
ac*100

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [ ]:
rfc.fit(xtrain,ytrain)
ypred = rfc.predict(xtest).reshape(-1,1)

In [ ]:
ac = rfc.score(xtrain,ytrain)
ac*100