In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv('Social_Network_Ads.csv')
df


User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
x=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values
x


array([['Male', 19L, 19000L],
       ['Male', 35L, 20000L],
       ['Female', 26L, 43000L],
       ...,
       ['Female', 50L, 20000L],
       ['Male', 36L, 33000L],
       ['Female', 49L, 36000L]], dtype=object)

from sklearn.preprocessing import Imputer


i=Imputer(missing_values='NaN',strategy='mean')
x[:,1:3]=i.fit_transform(x[:,1:3])
i=i.fit(x[:,1:3])
x[:,1:3]=i.transform(x[:,1:3])
print(x)


x[:,1:3]=i.fit_transform(x[:,1:3])
x

In [4]:
from sklearn.preprocessing import LabelEncoder as le
l=le()
x[:,0]=l.fit_transform(x[:,0])
x

array([[1, 19L, 19000L],
       [1, 35L, 20000L],
       [0, 26L, 43000L],
       ...,
       [0, 50L, 20000L],
       [1, 36L, 33000L],
       [0, 49L, 36000L]], dtype=object)

In [5]:
from sklearn.preprocessing import OneHotEncoder as oc
o=oc(categorical_features=[0])
x=o.fit_transform(x).toarray()
x

C:\Users\umama\Anaconda2\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\umama\Anaconda2\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0e+00, 1.0e+00, 1.9e+01, 1.9e+04],
       [0.0e+00, 1.0e+00, 3.5e+01, 2.0e+04],
       [1.0e+00, 0.0e+00, 2.6e+01, 4.3e+04],
       ...,
       [1.0e+00, 0.0e+00, 5.0e+01, 2.0e+04],
       [0.0e+00, 1.0e+00, 3.6e+01, 3.3e+04],
       [1.0e+00, 0.0e+00, 4.9e+01, 3.6e+04]])

In [6]:
from sklearn.model_selection import train_test_split as tt
xtrain, xtest,ytrain,ytest=tt(x,y,test_size=0.3)
xtest


array([[0.00e+00, 1.00e+00, 4.70e+01, 2.00e+04],
       [1.00e+00, 0.00e+00, 2.60e+01, 5.20e+04],
       [1.00e+00, 0.00e+00, 3.50e+01, 6.00e+04],
       [0.00e+00, 1.00e+00, 4.00e+01, 7.80e+04],
       [1.00e+00, 0.00e+00, 3.90e+01, 6.10e+04],
       [1.00e+00, 0.00e+00, 3.80e+01, 5.50e+04],
       [0.00e+00, 1.00e+00, 3.50e+01, 6.10e+04],
       [1.00e+00, 0.00e+00, 5.20e+01, 1.14e+05],
       [1.00e+00, 0.00e+00, 5.90e+01, 7.60e+04],
       [0.00e+00, 1.00e+00, 3.70e+01, 7.50e+04],
       [1.00e+00, 0.00e+00, 5.70e+01, 2.60e+04],
       [1.00e+00, 0.00e+00, 4.80e+01, 1.34e+05],
       [0.00e+00, 1.00e+00, 5.90e+01, 1.43e+05],
       [0.00e+00, 1.00e+00, 3.00e+01, 1.07e+05],
       [1.00e+00, 0.00e+00, 5.90e+01, 8.80e+04],
       [0.00e+00, 1.00e+00, 3.70e+01, 5.50e+04],
       [0.00e+00, 1.00e+00, 3.20e+01, 1.80e+04],
       [0.00e+00, 1.00e+00, 3.00e+01, 8.00e+04],
       [1.00e+00, 0.00e+00, 3.50e+01, 7.10e+04],
       [1.00e+00, 0.00e+00, 4.80e+01, 3.50e+04],
       [0.00e+00, 1.

In [7]:
from sklearn.preprocessing import StandardScaler as sc
s=sc()
xtrain=s.fit_transform(xtrain)
xtest=s.fit_transform(xtest)

print xtrain



[[-1.01438923  1.01438923  0.72350547 -1.09421789]
 [ 0.98581488 -0.98581488 -1.56017548 -0.02409891]
 [-1.01438923  1.01438923 -0.03772152  0.03535214]
 ...
 [ 0.98581488 -0.98581488 -0.7989485   0.421784  ]
 [ 0.98581488 -0.98581488  0.15258523  0.06507767]
 [ 0.98581488 -0.98581488 -0.41833501  1.31354982]]


from sklearn.preprocessing import StandardScaler as sc
s=sc()

xtrain=s.fit_transform(xtrain)
xtest=s.fit_transform(xtest)
xtrain


In [17]:
xtest.shape

(120L, 4L)

In [18]:
ytrain.shape

(280L,)

In [16]:
from sklearn.ensemble import RandomForestClassifier as rf
rfc = rf(n_estimators=1000)
rfc.fit(xtrain,ytrain)
ypred = rfc.predict(xtest)
ypred

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

In [17]:
from sklearn.metrics import confusion_matrix as cm
cm(ypred,ytest)

array([[69,  5],
       [ 6, 40]], dtype=int64)

In [ ]:
Decision tree classifier

In [37]:
from sklearn.tree import DecisionTreeClassifier as dt
dtc = dt()
dtc.fit(xtrain,ytrain)
ypred = dtc.predict(xtest)
ypred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [38]:
from sklearn.metrics import confusion_matrix as cm
cm(ypred,ytest)

array([[67, 16],
       [ 5, 32]], dtype=int64)

In [35]:
from sklearn.neighbors import KNeighborsClassifier as knn
knc = knn()
knc.fit(xtrain,ytrain)
ypred = knc.predict(xtest)
ypred

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0], dtype=int64)

In [36]:
from sklearn.metrics import confusion_matrix as cm
cm(ypred,ytest)

array([[68,  3],
       [ 4, 45]], dtype=int64)

In [19]:
from sklearn.naive_bayes import GaussianNB as gnb
nb = gnb()
nb.fit(xtrain,ytrain)
ypred = nb.predict(xtest)
ypred

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0], dtype=int64)

In [24]:
from sklearn.metrics import confusion_matrix as cm
cm(ypred,ytest)

array([[68, 12],
       [ 4, 36]], dtype=int64)

In [34]:
cm(ytest,ypred)

array([[68,  4],
       [12, 36]], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score as ac
ac = nb.score(xtest,ytest)
ac*100

86.66666666666667

In [33]:
t=ypred.iloc[:,ypred[0]=True]

SyntaxError: invalid syntax (<ipython-input-33-bceedfc93cd1>, line 1)

In [ ]:
from sklearn.svm import SVR
svr=SVR()


In [ ]:
svr.fit(xtrain,ytrain)
ypred = svr.predict(xtest).reshape(-1,1)
ypred


In [ ]:
ac = svr.score(xtrain,ytrain)
ac*100

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()


In [ ]:
dtc.fit(xtrain,ytrain)
ypred = dtc.predict(xtest).reshape(-1,1)
ypred


In [ ]:
ac = dtc.score(xtrain,ytrain)
ac*100

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [ ]:
rfc.fit(xtrain,ytrain)
ypred = rfc.predict(xtest).reshape(-1,1)

In [ ]:
ac = rfc.score(xtrain,ytrain)
ac*100