In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.preprocessing  

In [2]:
df=pd.read_csv('Salary_Data.csv')
df


YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
x=df.iloc[:,0].values
y=df.iloc[:,1].values
x


array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.2,  3.7,  3.9,
        4. ,  4. ,  4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,
        7.9,  8.2,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

from sklearn.preprocessing import Imputer


i=Imputer(missing_values='NaN',strategy='mean')
x[:,1:3]=i.fit_transform(x[:,1:3])
i=i.fit(x[:,1:3])
x[:,1:3]=i.transform(x[:,1:3])
print(x)


x[:,1:3]=i.fit_transform(x[:,1:3])
x

from sklearn.preprocessing import LabelEncoder as le
l=le()
x[:,0]=l.fit_transform(x[:,0])
x

from sklearn.preprocessing import OneHotEncoder as oc
o=oc(categorical_features=[0])
x=o.fit_transform(x).toarray()
x

In [4]:
from sklearn.model_selection import train_test_split as tt
xtrain, xtest,ytrain,ytest=tt(x,y,test_size=0.3)
ytest


array([ 67938.,  46205.,  43525., 112635.,  81363., 101302.,  37731.,
        54445.,  93940.])

from sklearn.preprocessing import StandardScaler as sc
s=sc()

xtrain=s.fit_transform(xtrain)
xtest=s.fit_transform(xtest)
xtrain


In [5]:
from sklearn.linear_model import LinearRegression as lr
rg = lr()
xtrain = xtrain.reshape(-1,1)
xtest = xtest.reshape(-1,1)
ytrain = ytrain.reshape(-1,1)
ytest = ytest.reshape(-1,1)
rg.fit(xtrain,ytrain)
ypred = rg.predict(xtest).reshape(-1,1)
ypred

array([[ 71652.9632106 ],
       [ 37099.61241635],
       [ 43818.31951523],
       [116764.2823031 ],
       [ 81251.11620901],
       [100447.42220582],
       [ 39019.24301603],
       [ 55336.10311332],
       [ 82210.93150885]])

In [6]:
from sklearn.metrics import accuracy_score as ac
ac = rg.score(xtrain,ytrain)
ac*100

95.5082293843243

In [16]:
from sklearn.linear_model import logistic

In [7]:
from sklearn.svm import SVR
svr=SVR()


In [8]:
svr.fit(xtrain,ytrain)
ypred = svr.predict(xtest).reshape(-1,1)
ypred


C:\Users\umama\Anaconda2\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\umama\Anaconda2\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


array([[64449.21883672],
       [64448.74630307],
       [64447.93929098],
       [64453.6241865 ],
       [64451.9424988 ],
       [64452.93900312],
       [64448.56370861],
       [64445.00000003],
       [64451.99615672]])

In [9]:
ac = svr.score(xtrain,ytrain)
ac*100

-25.50051170059082

In [10]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()


In [11]:
dtc.fit(xtrain,ytrain)
ypred = dtc.predict(xtest).reshape(-1,1)
ypred


array([[ 66029.],
       [ 39343.],
       [ 39891.],
       [116969.],
       [ 83088.],
       [113812.],
       [ 39343.],
       [ 64445.],
       [ 83088.]])

In [12]:
ac = dtc.score(xtrain,ytrain)
ac*100

95.23809523809523

In [13]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [14]:
rfc.fit(xtrain,ytrain)
ypred = rfc.predict(xtest).reshape(-1,1)

C:\Users\umama\Anaconda2\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\umama\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


In [15]:
ac = rfc.score(xtrain,ytrain)
ac*100

90.47619047619048