In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.preprocessing  

segregation

In [25]:
df=pd.read_csv('data.csv')
df
x=df.iloc[:,:-1].values
y=df.iloc[:,3].values
print(x)
print(y)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [26]:
from sklearn.preprocessing import Imputer


In [27]:
i=Imputer(missing_values='NaN',strategy='mean')
x[:,1:3]=i.fit_transform(x[:,1:3])
i=i.fit(x[:,1:3])
x[:,1:3]=i.transform(x[:,1:3])
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


C:\Users\umama\Anaconda2\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [5]:
x[:,1:3]=i.fit_transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [28]:
from sklearn.preprocessing import LabelEncoder as le
l=le()
x[:,0]=l.fit_transform(x[:,0])
print(x)



[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [7]:
from sklearn.preprocessing import OneHotEncoder as oc
o=oc(categorical_features=[0])#SELECT ONLY CATEGORICAL VARIABLES  
x=o.fit_transform(x).toarray()
print(x)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]


C:\Users\umama\Anaconda2\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\umama\Anaconda2\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
from sklearn.model_selection import train_test_split as tt
xtrain, xtest,ytrain,ytest=tt(x,y,test_size=0.3)
print ytest


['No' 'Yes' 'Yes']


In [11]:
from sklearn.preprocessing import StandardScaler as sc
s=sc()
xtrain=s.fit_transform(xtrain)
xtest=s.fit_transform(xtest)
print xtrain



[[ 1.15470054 -0.8660254  -0.40824829  1.08564479  1.07939634]
 [-0.8660254   1.15470054 -0.40824829 -0.175104   -0.31944297]
 [-0.8660254   1.15470054 -0.40824829 -1.75103999 -1.2179675 ]
 [-0.8660254  -0.8660254   2.44948974 -0.3677184  -1.4017566 ]
 [ 1.15470054 -0.8660254  -0.40824829  0.4552704   0.43613447]
 [-0.8660254   1.15470054 -0.40824829  1.40083199  1.44697456]
 [ 1.15470054 -0.8660254  -0.40824829 -0.6478848  -0.0233383 ]]
