In [2]:
import numpy as np
import pandas as pd

In [3]:
z=np.random.randn(5,5)
z

array([[-1.48186654,  0.54694087,  1.44976265,  0.19672942, -0.37390003],
       [ 0.54334767, -0.71353215, -1.00214627, -0.57617196, -1.44565225],
       [ 0.79926856,  0.60396377, -0.9812723 , -0.70335645, -1.63958245],
       [ 0.7164865 ,  1.00447569, -0.20749432,  1.11532654,  2.86842646],
       [ 1.67326257,  0.07649657,  1.54898291, -0.67990732,  0.03828184]])

In [4]:
l=[1,2,3,4,5]
s =np.array(l)
print(l)
print(s)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
print(np.arange(4,100,5))

[ 4  9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99]


In [6]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
from pandas import read_csv
a=pd.read_csv('')
read_csv.mean()
t=read_csv()
print(t)

IOError: [Errno 2] File  does not exist: ''